### ISSUE TITLE
Display different branches for docs

### ISSUE THREAD

**Issue by matks** [PrestaShop/core-weekly-generator#102]
On docs we have multiple branches: `1.7.x`, `8.x` ... one day `9.x`

Some PRs are backported so we need to display the PRs separated by branches. Else they look like they are duplicated
![Capture d’écran 2021-08-17 à 09 52 25](https://user-images.githubusercontent.com/3830050/129754909-7bd474c8-b0cd-4a6e-86e6-ee76b341c639.png)

**Comment by PierreRambaud** [comment]
Maybe we can find a way when the name is the same to request to PR and check commits? :sweat_smile:

**Comment by matks** [comment]
> Maybe we can find a way when the name is the same to request to PR and check commits? 😅

This will work if people are rigorous and do a cherry-pick while keeping the same PR name.
If they are lazy and they juste use github interface to create branches, this wont work 😅 

Also I think it's interesting for people to see changes for 1.7.x and changes for 8.x in the Core Weekly :) it shows what section of the documentation is evolving

**Comment by PierreRambaud** [comment]
I think it's the same for the Core developments. It's interesting to see which branch is affected and what it contains.
I maybe have an idea to implement it correctly :)

**Comment by matks** [comment]
Closed as this repository is about to be archived as a new [Core Generator](https://github.com/PrestaShop/presthubot/blob/master/src/App/Command/GitHubMonthlyReportCommand.php) has been constructed.
