### ISSUE TITLE
Duplicate Contributors

### ISSUE THREAD

**Issue by Progi1984** [PrestaShop/core-weekly-generator#19]
I think it's not normal to have multiples times the same contributor.

Example : https://build.prestashop.com/news/coreweekly-week-44-2019/

![image](https://user-images.githubusercontent.com/1533248/68373616-8b510200-0143-11ea-8067-51c19efc3dfb.png)

**Comment by matks** [comment]
Indeed. In my v2 I removed the duplicate before printing, but maybe Pierre's refactoring removed this.

**Comment by PierreRambaud** [comment]
I'm on it, I've a fix :)
