### ISSUE TITLE
Feature idea: provide weekly stats about PRs: averages, max, min, rises and lows

### ISSUE THREAD

**Issue by matks** [PrestaShop/core-weekly-generator#23]
The Core Weekly Generator already finds how many PRs and issues are opened/closed each weeky.
So we could record these stats to obtain some more stats
- average opened/closed PRs/issues by week on 3 last months, comparison with 3-months-period before
- average opened/closed PRs/issues by week on last year, comparison with year before
- does the number of opened/closed PRs/issues rises or lowers recently ?

**Comment by PierreRambaud** [comment]
Data can be retrieved and saved in this repository, with that, we are already able to generate stats per week: https://github.com/PrestaShop/core-weekly-generator#usage
We can improve this for date range, wdyt?

**Comment by matks** [comment]
Closed as this repository is about to be archived as a new [Core Generator](https://github.com/PrestaShop/presthubot/blob/master/src/App/Command/GitHubMonthlyReportCommand.php) has been constructed.
