### ISSUE TITLE
Feature idea: automatically select a GFI in the CW

### ISSUE THREAD

**Issue by LouiseBonnard** [PrestaShop/core-weekly-generator#76]
Some months ago, it has been decided to add a [good first issue](https://github.com/PrestaShop/PrestaShop/labels/good%20first%20issue) to each [Core Weekly](https://github.com/PrestaShop/prestashop.github.io/tree/master/news/_posts/core-weekly). Automatizing it would be great: pick a random good first issue and refers to it in the weekly report to facilitate the contribution!

**Comment by matks** [comment]
Closed as this repository is about to be archived as a new [Core Generator](https://github.com/PrestaShop/presthubot/blob/master/src/App/Command/GitHubMonthlyReportCommand.php) has been constructed.
