### ISSUE TITLE
In recent Core weekly the numbers about Pull request are wrong 

### ISSUE THREAD

**Issue by toutantic** [PrestaShop/core-weekly-generator#8]
See:
http://build.prestashop.com/news/coreweekly-week-37-2019/

72 new issues have been created in the project repositories;
64 issues have been closed, including 8 fixed issues on the core;
72 pull requests have been opened in the project repositories;
64 pull requests have been closed, including 8 merged pull requests.

We don't display the numbers about PR but reuse the numbers for the issues:
https://github.com/PrestaShop/core-weekly-generator/blob/master/core_weekly/__init__.py#L94

And when you follow the links under the PR you get different results.

**Comment by PierreRambaud** [comment]
Already fixed in #8

**Comment by matks** [comment]
I'll fix the reports.
Strange I did not notice, I checked several times 🤔looks like QA validation should always be done by someone else

**Comment by matks** [comment]
Fixed the reports in https://github.com/PrestaShop/prestashop.github.io/pull/591

@PierreRambaud found another bug. So there was 3 wrong numbers:
- X pull requests have been opened
- X pull requests have been closed (including X merged pull requests)

Those 3 X were wrong. Did you fix them all ?
